name: cloud-resume-challenge frontend
run-name: ${{ github.actor }} is testing GitHub actions.

on:
  push:
    branches:
    - main
    - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE


jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    environment: production
    # Permissions needed to interact with GitHub OIDC Token endpoint
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync ./website ${{ secrets.S3_BUCKET }} --delete
    - name: Create Cache Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION }} --paths "/*"
